# Generated by Django 3.2 on 2021-05-03 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twotter', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='img_name',
        ),
        migrations.AddField(
            model_name='user',
            name='user_img',
            field=models.ImageField(default='default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(help_text='YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.TextField(blank=True, help_text='Optional.', max_length=100),
        ),
    ]
